# This is a Minimal  workflow to help you deploy theme changes

name: Build and deploy to Github artifacts

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and deploy artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm install

      - name: Build artifacts for production
        run: npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: site-theme
          path: ${{ github.workspace }}/dist/**/*

      - name: Dispatch completed event (this is a workaround in order to access the artifact id)
        run: |
          curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
            --request POST \
            --data '{"event_type": "update_theme_config", "client_payload": { "deployed_theme_run_id": "${{ github.run_id }}" } }' \
            ${{ github.api_url }}/repos/${{ github.repository }}/dispatches
